Repository 0xsambit/winix, pull requests merged in 2025-07, with the labels that each got.

#15 docs: add Windows Internals Learning Doc with Rust FFI examples and best practices ( closes #1 )
  WINDOWS_INTERNALS.md
  src/process.rs
Labels: gssoc25, level1

#28 Fix: #27 - Add missing winapi features for kill.rs import resolution
  Cargo.lock
  Cargo.toml
  src/chmod.rs
  src/chown.rs
  src/commands/mod.rs
  src/disown.rs
  src/kill.rs
  src/lib.rs
  src/main.rs
  src/process.rs
  src/sudo.rs
  src/tui.rs
  tests/process.rs
Labels: bug, gssoc25, level2

#32 make process.rs cross-platform by isolating Windows-specific code(resolves #18)
  Cargo.lock
Labels: bug, gssoc25, level1

#39 feat: add support for cat and rm commands (#38)
  s1.txt
  s2.txt
  src/cat.rs
  src/lib.rs
  src/main.rs
  src/rm.rs
  test2.txt
  tests/cat_test.rs
  tests/rm_test.rs
Labels: coreutils, gssoc25, level2

#41 fix(touch.rs) issues
  src/main.rs
  src/touch.rs
  tests/touch_test.rs
Labels: bug

#44 feat: Add comprehensive async/await and Stream support with new commands ( closes #11 )
  Cargo.lock
  Cargo.toml
  README.md
  src/cat.rs
  src/grep.rs
  src/head.rs
  src/lib.rs
  src/main.rs
  src/pipeline.rs
  src/tail.rs
  src/touch.rs
  tests/ansi_test.rs
  tests/async_commands_test.rs
  tests/cat_test.rs
  tests/echo_test.rs
Labels: coreutils, gssoc25, level3

#45 Solved Support Line Editing, History & Completion via rustyline #17
  .history.txt
  Cargo.lock
  Cargo.toml
  src/input.rs
  src/lib.rs
  src/main.rs
  tests/input_test.rs
Labels: coreutils, gssoc25, level3

#51 Fix/chmod
  Cargo.toml
  src/cat.rs
  src/chmod.rs
  src/input.rs
  src/lib.rs
  src/main.rs
  src/process.rs
  src/touch.rs
  tests/cat_test.rs
Labels: bug, gssoc25, level1
